spring:
  profiles:
    include: private

caregiver:
  aws:
    signing-region: ap-northeast-1
    access-key: ${caregiver.aws.secret-key}
    secret-key: ${caregiver.aws.access-key}
    sns:
      arn: ${caregiver.aws.sns.arn}
