spring:
  profiles:
    include: private

caregiver:
  aws:
    #service-endpoint:
    signing-region: ap-northeast-2
    access-key: ${caregiver.aws.secret-key}
    secret-key: ${caregiver.aws.access-key}
    sns:
      arn: ${caregiver.aws.sns.arn}


