spring:
  profiles:
    include: s3-private

cloud:
  aws:
    s3:
      image-path: image/
      bucket: caregiver-salon
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${caregiver.aws.secret-key}
      secret-key: ${caregiver.aws.access-key}
    stack:
      auto: false

logging.level.com.amazonaws.util.EC2MetadataUtils: error
