cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAYXA537A74IOP4V27
      secret-key: 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
aws:
  s3:
    image:
      bucket: s3://caregiver-salon/image/
